### ISSUE TITLE
Unable to add defs to DescriptorPool: out of memory (Google::Protobuf::TypeError)

### ISSUE THREAD

**Issue by bilby91** [EnjoyTech/apollo-studio-tracing-ruby#9]
Hello,

I'm running an issue when trying to start a rails server after adding the gem in the project. It seems to be related to the following issues but I haven't been able to figure out a workaround yet.

Related issues:

- https://github.com/ruby-protobuf/protobuf/issues/381
- https://github.com/protocolbuffers/protobuf/pull/2478

The stacktrace:

```
bash-5.0# bundle exec rails s -b 0.0.0.0
Traceback (most recent call last):
	61: from bin/rails:6:in `<main>'
	60: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	59: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	58: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	57: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	56: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	55: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	54: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	53: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	52: from /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<main>'
	51: from /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command.rb:50:in `invoke'
	50: from /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/command/base.rb:69:in `perform'
	49: from /bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	48: from /bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	47: from /bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	46: from /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/commands/server/server_command.rb:135:in `perform'
	45: from /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/commands/server/server_command.rb:135:in `tap'
	44: from /bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/commands/server/server_command.rb:138:in `block in perform'
	43: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	42: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	41: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	40: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	39: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	38: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	37: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	36: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	35: from /var/www/app/config/application.rb:15:in `<main>'
	34: from /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
	33: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	32: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	31: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	30: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	29: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	28: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from /bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing.rb:3:in `<main>'
	22: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	21: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	20: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	19: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	18: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	17: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	16: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	15: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	14: from /bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing/proto.rb:3:in `<main>'
	13: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	12: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	11: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	10: from /bundle/ruby/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	 9: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 8: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 7: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 6: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 5: from /bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 4: from /bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing/proto/apollo_pb.rb:7:in `<main>'
	 3: from /bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing/proto/apollo_pb.rb:7:in `build'
	 2: from /bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing/proto/apollo_pb.rb:7:in `instance_eval'
	 1: from /bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing/proto/apollo_pb.rb:8:in `block in <main>'
/bundle/ruby/2.7.0/gems/apollo-studio-tracing-1.0.1/lib/apollo-studio-tracing/proto/apollo_pb.rb:8:in `add_file': Unable to add defs to DescriptorPool: out of memory (Google::Protobuf::TypeError)
```

**Comment by lsanwick** [comment]
Thanks for the report! Is there any chance you can provide a repro case in the form of a repo?

**Comment by bilby91** [comment]
Will see if I can reproduce it outside of my project!
